### ISSUE TITLE
removeViewerInputHook ?

### ISSUE THREAD

**Issue by avandecreme** [msalsbery/OpenSeadragonViewerInputHook#1]
Would that be possible to add a removeViewerInputHook method? :)

**Comment by dehuszar** [comment]
I would also like this

**Comment by tamarmot** [comment]
+1

**Comment by ruisilva450** [comment]
@msalsbery So, will you do it?

**Comment by pwiegardt** [comment]
This feature would be very much appreciated. Can someone at least provide a workaround?

**Comment by msalsbery** [comment]
Closing this...

The new home for the OpenSeadragon Imaging plugins is here: https://github.com/openseadragon-imaging

The new destroy() methods in the plugins now allows for this!
