### ISSUE TITLE
Uncaught TypeError: a is not a function

### ISSUE THREAD

**Issue by sandymclean** [msalsbery/OpenSeadragonViewerInputHook#5]
Line 29 of openseadragon-viewerinputhook.min.js is throwing this error.

Here is the line of code in question: var d = a(c);

I am implementing a very basic hook to disable the default zoom on click, which is actually part of the example in the documentation. The hook works, but in console everytime I click it generates this error.

Uncaught TypeError: a is not a functionb.ViewerInputHook.callHandlers @ openseadragon-viewerinputhook.min.js:29b.ViewerInputHook.b.(anonymous function) @ openseadragon-viewerinputhook.min.js:19jb @ openseadragon.min.js:1284H @ openseadragon.min.js:993G @ openseadragon.min.js:982a.MouseTracker.ob.(anonymous function).mouseupcaptured @ openseadragon.min.js:1484

**Comment by sandymclean** [comment]
Using non-minified plug-in code, following trace:

Uncaught TypeError: hookHandler is not a function$.ViewerInputHook.callHandlers @ openseadragon-viewerinputhook.js:132$.ViewerInputHook.tracker.(anonymous function) @ openseadragon-viewerinputhook.js:105jb @ openseadragon.min.js:1284H @ openseadragon.min.js:993G @ openseadragon.min.js:982a.MouseTracker.ob.(anonymous function).mouseupcaptured @ openseadragon.min.js:1484

**Comment by brennanreese** [comment]
msalsbery have you looked into this yet? not sure why hookHandler would not be recognized?

**Comment by msalsbery** [comment]
@sandymclean Can you show the code you're using please? I'm not getting an error here.

**Comment by msalsbery** [comment]
@sandymclean @brennanreese 

Sorry for the extreme delay responding!

Is this still an issue anywhere? I've never seen it occur on my end.

Cheers!

**Comment by msalsbery** [comment]
Closing this....

The new home for the OpenSeadragon Imaging plugins is here: https://github.com/openseadragon-imaging
