### ISSUE TITLE
use npm to install

### ISSUE THREAD

**Issue by darbychang** [msalsbery/OpenSeadragonViewerInputHook#7]
Hi, is it possible to publish this plugin as a npm module so that users can install this plugin via npm? I cannot simply do it and send you a pull request since this operation is not code editing. Let me know if you'd like to do this in a near future. If not, I could publish one later and give you it if you want (I'm not sure how to transfer npm ownership, but it should be possible).

**Comment by msalsbery** [comment]
@darbychang and all...

Now that OpenSeadragon is available on npm I suppose I should get on board and publish my plugins there. Thanks for the suggestion...queued to my TODO list!

**Comment by msalsbery** [comment]
@darbychang Done, finally!

The new home for the OpenSeadragon Imaging plugins is here: https://github.com/openseadragon-imaging

The npm packages are up to date, and can be found here: https://www.npmjs.com/settings/openseadragon-imaging/packages

Note: there's now destroy() method(s) which should be used before calling OpenSeadragon.Viewer.destroy()...cleans up memory nicely for long-running SPAs (like React apps)
