### ISSUE TITLE
`event.preventDefaultAction = true` param doesn't appear to work for most handlers

### ISSUE THREAD

**Issue by dehuszar** [msalsbery/OpenSeadragonViewerInputHook#9]
The documentation indicates that setting `event.preventDefaultAction = true` and stating `return true` in the event handlers for click, drag, and scroll events, will prevent the viewer action but allow the original event to continue propagating to the event source.  However, I'm finding this to only be true in the nonPrimaryPressHandler, and nonPrimaryReleaseHandler.  I am able to confirm that I can enter into the hook functions for each event type handled.

Thus far I have tried to prevent the default viewer events in the click, drag, move, press/release (and non), and scroll handlers.  I am able to prevent the viewer actions, but none of the hooks (besides right-click initiated events) seem to allow the original event to pass through to the event listeners bound to my viewer's children (custom overlays).

I am using OSD 2.2.1

**Comment by msalsbery** [comment]
@dehuszar Sorry for the extreme delay...these plugins definitely fell to the side for quite a while.

For what it's worth, I'm currently updating and fixing these issues, and the plugins now have a new home: https://github.com/openseadragon-imaging

Still in the process of getting all the links to builds and documentation updated, but the latest plugin code can be found there. Most important new feature is destroy() methods...the references these hook plugins kept to OpenSeadragon were preventing memory cleanup, which wasn't good for long running single page applications...

**Comment by dehuszar** [comment]
No worries, I was just doing some housekeeping.  I realized this was no
longer in my radar and may have already been fixed, so I closed this and
several other old issues filed elsewhere.

Best,
Sam
